name: Integración continua

on:
  push:
    branches: [ main ]
    paths: [ 'hangman-front/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'hangman-front/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    