name: Integración continua

on:
  push:
    branches: [ main ]
    paths: [ 'hangman-front/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'hangman-front/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Node.js version
      uses: actions/setup-node@v6





    